from mWindowsSDK import *;

dsThreadAccessRightName_by_uFlag = {
  DELETE: "DELETE",
  READ_CONTROL: "READ_CONTROL",
  SYNCHRONIZE: "SYNCHRONIZE",
  THREAD_DIRECT_IMPERSONATION: "THREAD_DIRECT_IMPERSONATION",
  THREAD_GET_CONTEXT: "THREAD_GET_CONTEXT",
  THREAD_IMPERSONATE: "THREAD_IMPERSONATE",
  THREAD_QUERY_INFORMATION: "THREAD_QUERY_INFORMATION",
  THREAD_QUERY_LIMITED_INFORMATION: "THREAD_QUERY_LIMITED_INFORMATION",
  THREAD_SET_CONTEXT: "THREAD_SET_CONTEXT",
  THREAD_SET_INFORMATION: "THREAD_SET_INFORMATION",
  THREAD_SET_LIMITED_INFORMATION: "THREAD_SET_LIMITED_INFORMATION",
  THREAD_SET_THREAD_TOKEN: "THREAD_SET_THREAD_TOKEN",
  THREAD_SUSPEND_RESUME: "THREAD_SUSPEND_RESUME",
  THREAD_TERMINATE: "THREAD_TERMINATE",
  WRITE_DAC: "WRITE_DAC",
  WRITE_OWNER: "WRITE_OWNER",
};

def fsGetThreadAccessRightsFlagsDescription(uFlags):
  if uFlags == THREAD_ALL_ACCESS:
    return "THREAD_ALL_ACCESS";
  return " | ".join([s for s in [
    sFlagName if uFlags & uFlag != 0 else None
    for (uFlag, sFlagName) in dsThreadAccessRightName_by_uFlag.items()
  ] if s]);
